name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true

  integration-tests:
    name: Cross Browser Tests
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
    - name: Browserstack
      run: npm run test:browserstack
      env:
        BROWSERSTACK_USERNAME: dylanschiemann2
        BROWSERSTACK_ACCESS_KEY: 4Q2g8YAc9qeZzB2hECnS
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/coverage.json
        fail_ci_if_error: true
