language: node_js
node_js:
  - node
  - lts/*
  - 13
  - 10
  - 6
script:
- npm run test
- npm run build
- npm run test:examples
branches:
  only:
  - master
env:
  global:
    secure: nAiPtzlfaT+NE8thcb0CFO8m0K/hzHVlnoaoxlD1Y7tWTIWarMXaOEGPjySWJAXb/zH1Ntm677sRRhghfCImiDoTDFHjXZfGqYNudsn/2X7MAUXaZBHfrNFTDU7aJnfygCWyXOSMlqAesPo+Ux0puZHeE/BZr37x985YJ0bwgl18rac2kHtvKxnSEGm5eQfaNJx77ayG+6w6Q1BsjhdxTbNhF5Q2+trSfUhmjT2jBMjje82SM0Z2GgmAIRGZFybQvE0793nxLHnBNqlPD+88Zo8oOiQbHC96BZtCTOVdqKrlKXMFh/Ryomm9FJqYYCkumb3vpHM35GklnKUlvkGbijz1+8yFWCQ5Y+FiEvSbjEr0Ki1rcC5q43ntREoVUHAAqfD6u5k6DrodIfzf+RJGJq1YZZI4RUO734X8d7Bwbrqa6xhcxP6v9K8+hx7dLtmEHCHV0hRntzvzIMYhnQSr5zpzyd8Owa0xODh7x648CAJX7NDH5mBqlFdOS6JbhVAQ+f3ZmV8ij/6xphvPbR0U9+yLiM/VBuWsi53Onpwg+KH+4K9xrzCwJlW81Rv13RIsdsptndYIrnujcfOLRTkZNjKR0SB7SS95q1xN4u8aGdHCdiXyBol6Q0KQV2ZgRfBdCxlkmoB1uTGdNLTiQI0ARRuMFN0duQQyDThgXRBhUSc=
